version: 2.1

parameters:
  node-image-tag:
    type: string
    default: "20.10.0"
  resource-class:
    type: string
    default: "medium"
  yarn-version:
    type: string
    default: "4.2.2"

orbs:
  coveralls: coveralls/coveralls@2.2.1

commands:
  install-yarn:
    description: "Install Yarn"
    steps:
      - run: corepack enable
      - run: yarn set version << pipeline.parameters.yarn-version >>
  install-dependencies:
    description: "Install Dependencies"
    steps:
      - run: yarn install

jobs:
  coverage:
    docker:
      - image: cimg/node:<< pipeline.parameters.node-image-tag >>
    resource_class: << pipeline.parameters.resource-class >>
    steps:
      - checkout
      - install-yarn
      - install-dependencies
      - run:
          name: Run Code Coverage
          command: yarn coverage
      - run:
          name: Generate Code Coverage lcov File
          command: yarn workspace prosemirror-jdita run nyc --reporter=text-lcov report > coverage.lcov
      - coveralls/upload:
          coverage_file: coverage.lcov
  generate-docs:
    docker:
      - image: cimg/node:<< pipeline.parameters.node-image-tag >>
    resource_class: << pipeline.parameters.resource-class >>
    steps:
      - checkout
      - install-yarn
      - install-dependencies
      - run:
          name: Generate Docs
          command: yarn generate-docs
  build:
    docker:
      - image: cimg/node:<< pipeline.parameters.node-image-tag >>
    resource_class: << pipeline.parameters.resource-class >>
    steps:
      - checkout
      - install-yarn
      - install-dependencies
      - run:
          name: build
          command: yarn build
  build-demo:
    docker:
      - image: cimg/node:<< pipeline.parameters.node-image-tag >>
    resource_class: << pipeline.parameters.resource-class >>
    steps:
      - checkout
      - install-yarn
      - install-dependencies
      - run:
          name: build-demo
          command: yarn build:demo
workflows:
  build-and-test:
    jobs:
      - coverage
      - generate-docs
      - build
      - build-demo
