version: 2.1

parameters:
  node-image-tag:
    type: string
    default: "20.10.0"
  resource-class:
    type: string
    default: "small"
  pkg-manager:
    type: string
    default: "yarn-berry"
  pkg-cache-version:
    type: string
    default: "v4"

orbs:
  node: circleci/node@5.2.0

jobs:
  clone-and-install:
    docker:
      - image: cimg/node:<< pipeline.parameters.node-image-tag >>
    resource_class: << pipeline.parameters.resource-class >>
    steps:
      - checkout
      - node/install-packages:
          check-cache: always
          cache-version: << pipeline.parameters.pkg-cache-version >>
          pkg-manager: << pipeline.parameters.pkg-manager >>
          with-cache: false
workflows:
  build-and-test:
    jobs:
      - clone-and-install
      - node/run:
          name: build
          requires:
            - clone-and-install
          version: << pipeline.parameters.node-image-tag >>
          resource_class: << pipeline.parameters.resource-class >>
          pkg-manager: << pipeline.parameters.pkg-manager >>
          setup:
            - node/install-packages:
                check-cache: always
                cache-version: << pipeline.parameters.pkg-cache-version >>
                pkg-manager: << pipeline.parameters.pkg-manager >>
                with-cache: false
          yarn-run: build
      - node/run:
          name: build:demo
          requires:
            - clone-and-install
          version: << pipeline.parameters.node-image-tag >>
          resource_class: << pipeline.parameters.resource-class >>
          pkg-manager: << pipeline.parameters.pkg-manager >>
          setup:
            - node/install-packages:
                check-cache: always
                cache-version: << pipeline.parameters.pkg-cache-version >>
                pkg-manager: << pipeline.parameters.pkg-manager >>
                with-cache: false
          yarn-run: build:demo
      - node/run:
          name: coverage
          requires:
            - clone-and-install
          version: << pipeline.parameters.node-image-tag >>
          resource_class: << pipeline.parameters.resource-class >>
          pkg-manager: << pipeline.parameters.pkg-manager >>
          setup:
            - node/install-packages:
                check-cache: always
                cache-version: << pipeline.parameters.pkg-cache-version >>
                pkg-manager: << pipeline.parameters.pkg-manager >>
                with-cache: false
          yarn-run: coverage
      - node/run:
          name: generate docs
          requires:
            - clone-and-install
          version: << pipeline.parameters.node-image-tag >>
          resource_class: << pipeline.parameters.resource-class >>
          pkg-manager: << pipeline.parameters.pkg-manager >>
          setup:
            - node/install-packages:
                check-cache: always
                cache-version: << pipeline.parameters.pkg-cache-version >>
                pkg-manager: << pipeline.parameters.pkg-manager >>
                with-cache: false
          yarn-run: generate-docs