version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  clone-and-install:
    docker:
     - image: cimg/node:12.13.1
    steps:
      - checkout
      - node/install-yarn:
        version: 1.22.21
      - node/install-packages:
          pkg-manager: yarn 
workflows:
  build-and-test:
    jobs:
      - clone-and-install
      - node/run:
        yarn-run: build
      - node/run:
        yarn-run: build:demo
      - node/run:
        yarn-run: coverage