version: 2.1

parameters:
  node-image-tag:
    type: string
    default: "20.10.0"
  yarn-version:
    type: string
    default: "1.22.21"
  resource-class:
    type: string
    default: "small"

orbs:
  node: circleci/node@5.1.1
  cypress: cypress-io/cypress@3
jobs:
  clone-and-install:
    docker:
     - image: cimg/node:<< pipeline.parameters.node-image-tag >>
    resource_class: << pipeline.parameters.resource-class >>
    steps:
      - checkout
      - node/install-yarn:
          version: << pipeline.parameters.yarn-version >>
      - node/install-packages:
          pkg-manager: yarn 
  run-cypress-in-specified-node-version:
    executor:
      name: cypress/default
      node-version: "20.10.0"
    steps:
      - cypress/install:
          package-manager: "yarn"
      - cypress/run-tests:
          start-command: yarn run start:demo
          cypress-command: yarn run test:demo
workflows:
  build-and-test:
    jobs:
      - clone-and-install
      - node/run:
          name: build
          requires:
            - clone-and-install
          version: << pipeline.parameters.node-image-tag >>
          resource_class: << pipeline.parameters.resource-class >>
          pkg-manager: yarn
          setup:
            - node/install-yarn:
                version: << pipeline.parameters.yarn-version >>
          yarn-run: build
      - node/run:
          name: build:demo
          requires:
            - clone-and-install
          version: << pipeline.parameters.node-image-tag >>
          resource_class: << pipeline.parameters.resource-class >>
          pkg-manager: yarn
          setup:
            - node/install-yarn:
                version: << pipeline.parameters.yarn-version >>
          yarn-run: build:demo
      - node/run:
          name: coverage
          requires:
            - clone-and-install
          version: << pipeline.parameters.node-image-tag >>
          resource_class: << pipeline.parameters.resource-class >>
          pkg-manager: yarn
          setup:
            - node/install-yarn:
                version: << pipeline.parameters.yarn-version >>
          yarn-run: coverage
      - node/run:
          name: generate docs
          requires:
            - clone-and-install
          version: << pipeline.parameters.node-image-tag >>
          resource_class: << pipeline.parameters.resource-class >>
          pkg-manager: yarn
          setup:
            - node/install-yarn:
                version: << pipeline.parameters.yarn-version >>
          yarn-run: generate-docs
      - node/run:
          name: lint
          requires:
            - clone-and-install
          version: << pipeline.parameters.node-image-tag >>
          resource_class: << pipeline.parameters.resource-class >>
          pkg-manager: yarn
          setup:
            - node/install-yarn:
                version: << pipeline.parameters.yarn-version >>
          yarn-run: lint
      - run-cypress-in-specified-node-version:
          name: Run Cypress test